### create user
POST http://localhost:8080/user/submit-form
Content-Type: application/json

{
  "userId": "test12",
  "password": "content",
  "nickName": "test123",
  "phoneNumber": "01053305064"
}

### verigy user phoneNumber
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "verifyCode": "443516"
}

###  user login
POST http://localhost:8080/login
Content-Type: application/json

{
  "userId": "test12",
  "password": "content"
}