### create user
POST http://localhost:8080/user/submit-form
Content-Type: application/json

{
  "userId": "test12",
  "password": "content",
  "nickName": "test123",
  "phoneNumber": "01053305064"
}

### verigy user phoneNumber
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "verifyCode": "238095"
}

###  user login
POST http://localhost:8080/login
Content-Type: application/json

{
  "userId": "test12",
  "password": "content"
}

### user info get
GET http://localhost:8080/user/test12
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJ0ZXN0MTIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMzAxMzQ4MSwiZXhwIjoxNzIzMDQ5NDgxfQ.fngsrAG3R1e5OR0P9w1LB09Xh0fhwBg8yOax0PQ55fM

### user delete
DELETE http://localhost:8080/user/test12
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJ0ZXN0MTIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMjkyNzgxOCwiZXhwIjoxNzIyOTYzODE4fQ._zV9AZbIrj-btO6m1hVyqiGu6tNRLKMATWYC2c2B4IM

### user info update
PATCH http://localhost:8080/user/testinfo3/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJ0ZXN0MTIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMjkzMDg4NywiZXhwIjoxNzIyOTY2ODg3fQ.sweqyR1WGyeCWfCkTLaUq331d37Fg_YLbVWgTJ6b7hA

{
  "userId": "testinfo2",
  "nickName": "testinf2"
}

### user password update
PATCH http://localhost:8080/user/test12/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJ0ZXN0MTIiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMjkzMDg4NywiZXhwIjoxNzIyOTY2ODg3fQ.sweqyR1WGyeCWfCkTLaUq331d37Fg_YLbVWgTJ6b7hA

{
  "passwordBefore": "content",
  "passwordAfter": "12341234",
  "passwordDoubleCheck": "12341234"
}