spring:
  datasource:
    url: jdbc:h2:mem:test
    username: kyuwon
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      port: 6379
      host: localhost
      password: tlarb3011
redisson:
  config:
    singleServerConfig:
      address: "redis://localhost:6379"
      password: tlarb3011
jwt:
  secret: rjsrnreogkrrytlarbdnjsdlqslekrkatkgkqslekaaavvvvvvrlrlrldjfuqwl
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET_NAME}
#spring:
#  datasource:
#    url: jdbc:mysql://kwon-db.cjm4g2ggcx4k.ap-northeast-2.rds.amazonaws.com:3306/owoonwan?useSSL=false&serverTimezone=Asia/Seoul
#    username: admin
#    password: tlarb3011
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#server:
#  port: 80