spring:
  datasource:
    url: jdbc:h2:mem:test
    username: kyuwon
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#spring:
#  datasource:
#    url: jdbc:mysql://kwon-db.cjm4g2ggcx4k.ap-northeast-2.rds.amazonaws.com:3306/owoonwan?useSSL=false&serverTimezone=Asia/Seoul
#    username: admin
#    password: tlarb3011
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#server:
#  port: 80